path: G:/XR_Xray_Detection/datasets/PIDray_yolo
train: train.txt
val: hard.txt
test: hard.txt
nc: 12
channels: 4
xr_pcn: true
xr_egi: true
names: ['Baton', 'Plier', 'Hammer', 'Powerbank', 'Scissors', 'Wrench', 'Gun', 'Bullet', 'Sprayer', 'HandCuffs', 'Knife', 'Lighter']
